
#java -jar -Dspring.profiles.active=dev

server:
  port: 1112
  session:
    timeout: 60000
    
logging:
  path: /home/dev/logs/
  level:
    org.springframework.web: INFO
    com.app: DEBUG
    
file:
  upload:
    path: /home/dev/upload_img/
    
# DATABASE
spring:
  mariadb:
    awareness:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://server_ip:3306/awareness
      url-option: ?useUnicode=true&characterEncoding=utf-8&interactiveClient=true&autoReconnect=true&autoReconnectForPools=true&useSSL=false
      username: root
      password: password1
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
      max-wait: 3000
  mssql:
    mssql1:
      driver-class-name: net.sourceforge.jtds.jdbc.Driver
      url: jdbc:jtds:sqlserver://server_ip:1433;databaseName=mssql1
      url-option:
      username: user1
      password: password1
      initialSize: 10
      maxActive: 10
      maxIdle: 10
      minIdle: 10
      maxWait: 3000
      validationQuery: SELECT 1
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 600000
    mssql2:
      driver-class-name: net.sourceforge.jtds.jdbc.Driver
      url: jdbc:jtds:sqlserver://server_ip:1433;databaseName=mssql2
      url-option:
      username: user1
      password: password1
      initialSize: 10
      maxActive: 10
      maxIdle: 10
      minIdle: 10
      maxWait: 3000
      validationQuery: SELECT 1
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 600000
    mssql3:
      driver-class-name: net.sourceforge.jtds.jdbc.Driver
      url: jdbc:jtds:sqlserver://server_ip:1433;databaseName=mssql3
      url-option:
      username: user1
      password: password1
      initialSize: 10
      maxActive: 10
      maxIdle: 10
      minIdle: 10
      maxWait: 3000
      validationQuery: SELECT 1
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 600000

    